// File generated by Gemini CLI for development environment.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps in development environment.
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // macOS options from iOS
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY1y7xckabw1gMht8PQfab8Vv4tMp0Sjg',
    appId: '1:233008946230:android:32baafdf5d7ac5796a4c97',
    messagingSenderId: '233008946230',
    projectId: 'go-mobile-dev-ce2ac',
    storageBucket: 'go-mobile-dev-ce2ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6aprITxHiDEKJugV1IlZFUghLkpIf_xs',
    appId: '1:233008946230:ios:827ee0bc325749b66a4c97',
    messagingSenderId: '233008946230',
    projectId: 'go-mobile-dev-ce2ac',
    storageBucket: 'go-mobile-dev-ce2ac.firebasestorage.app',
    iosBundleId: 'com.japan-blue.go-mobile',
  );
}
