// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEqCwLje7F7-b-_CZLKKRp3vNSZIMl0AI',
    appId: '1:65724819181:android:56368fc1edae679d530ee4',
    messagingSenderId: '65724819181',
    projectId: 'go-mobile-cb9f1',
    storageBucket: 'go-mobile-cb9f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhLZ26u1nCnKkpvDkz3gf94FMc6XJun8Q',
    appId: '1:65724819181:ios:b0ba58a08634b8df530ee4',
    messagingSenderId: '65724819181',
    projectId: 'go-mobile-cb9f1',
    storageBucket: 'go-mobile-cb9f1.firebasestorage.app',
    iosBundleId: 'com.japan-blue.go-mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhLZ26u1nCnKkpvDkz3gf94FMc6XJun8Q',
    appId: '1:65724819181:ios:b0ba58a08634b8df530ee4',
    messagingSenderId: '65724819181',
    projectId: 'go-mobile-cb9f1',
    storageBucket: 'go-mobile-cb9f1.firebasestorage.app',
    iosBundleId: 'com.japan-blue.go-mobile',
  );
}